name: orientation_app
description: "Daystar University's orientation application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6 
  http: ^1.2.2
  lottie: ^3.1.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  

flutter:
  uses-material-design: true
  fonts:
  - family:  MyFlutterApp
    fonts:
      - asset: fonts/MyFlutterApp.ttf

  assets:
    - assets/images/
    - assets/lotties/

    
